# Generated by Django 4.0.4 on 2022-05-13 06:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='actors',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='director',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='favorites',
            field=models.ManyToManyField(auto_created=True, blank=True, related_name='favorites', to='main.user'),
        ),
        migrations.AddField(
            model_name='movies',
            name='images',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='movies',
            name='language',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='production',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='released',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='year',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
