# Generated by Django 4.0.4 on 2022-05-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_movies_actors_movies_country_movies_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.IntegerField(max_length=200),
        ),
    ]
