# Generated by Django 4.0.4 on 2022-05-20 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_remove_movies_favorites_favorites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['comment']},
        ),
        migrations.AddField(
            model_name='movies',
            name='favorites',
            field=models.ManyToManyField(auto_created=True, blank=True, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
